### ISSUE TITLE
Example files are installed using cp and do not have the right permissions

### ISSUE THREAD

**Issue by ghost** [uzbl/uzbl#403]
I followed the instructions given [here](https://www.uzbl.org/get.php):
```
[/tmp/download]: git clone git://github.com/uzbl/uzbl.git
Cloning into 'uzbl'...
remote: Counting objects: 22234, done.
remote: Total 22234 (delta 0), reused 0 (delta 0), pack-reused 22234
Receiving objects: 100% (22234/22234), 7.17 MiB | 2.89 MiB/s, done.
Resolving deltas: 100% (12980/12980), done.
[/tmp/download]: cd uzbl/
[/tmp/download/uzbl]: make
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/uzbl-core.o src/uzbl-core.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/comm.o src/comm.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/commands.o src/commands.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/events.o src/events.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/gui.o src/gui.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/inspector.o src/inspector.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/io.o src/io.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/js.o src/js.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/requests.o src/requests.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/scheme.o src/scheme.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/status-bar.o src/status-bar.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/util.o src/util.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/variables.o src/variables.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/3p/async-queue-source/rb-async-queue-watch.o src/3p/async-queue-source/rb-async-queue-watch.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/cookie-jar.o src/cookie-jar.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/scheme-request.o src/scheme-request.c
cc -std=c99 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -ggdb -W -Wall -Wextra -pthread -Wunused-function -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-47-gbdbb81ab\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/soup.o src/soup.c
rm -f libuzbl.a
ar cr libuzbl.a src/comm.o src/commands.o src/events.o src/gui.o src/inspector.o src/io.o src/js.o src/requests.o src/scheme.o src/status-bar.o src/util.o src/uzbl-core.o src/variables.o src/3p/async-queue-source/rb-async-queue-watch.o src/cookie-jar.o src/scheme-request.o src/soup.o
cc   src/uzbl-core.o libuzbl.a  -lwebkitgtk-1.0 -ljavascriptcoregtk-1.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lsoup-2.4 -lgthread-2.0 -pthread -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lX11  -o uzbl-core
VERSION=0.9.1+47.gbdbb81ab python3 setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
Makefile:144: recipe for target 'dist/uzbl-0.9.1+47.gbdbb81ab-py3-none-any.whl' failed
make: *** [dist/uzbl-0.9.1+47.gbdbb81ab-py3-none-any.whl] Error 1
[/tmp/download/uzbl]: 
```
Can you help?

**Comment by ghost** [comment]
The system is openSUSE Leap 42.3 (in case that matters).

**Comment by mathstuf** [comment]
Hmm, it seems that the `wheel` Python package is missing. I suppose we should add a `requirements.txt` to make it easy to get them.

**Comment by ghost** [comment]
In YaST I see `python-wheel` and `python3-wheel`. Which one do I need?

**Comment by keis** [comment]
python3 is the one you want

**Comment by ghost** [comment]
Thanks. Now `make` and `make install` worked but when I try to start the program:
```
[~]: uzbl-browser 
Error: Global config not found; please check if your distribution ships them separately
[~]: which uzbl-browser 
/usr/local/bin/uzbl-browser
```
What should I do?

**Comment by mathstuf** [comment]
A configuration file wasn't found. It seems the example config wasn't installed (it should be `/usr/loca/share/uzbl/examples/config/config`).

**Comment by ghost** [comment]
So the installer needs fixing?

**Comment by mathstuf** [comment]
Probably. Does that file show up anywhere in under `/usr/local`?

**Comment by ghost** [comment]
```
# tree /usr/local/share/uzbl/
/usr/local/share/uzbl/
├── docs
│   ├── AUTHORS
│   ├── COMMUNITY.md
│   ├── CONTRIBUTING.md
│   ├── FAQ.md
│   ├── INSTALL.md
│   ├── KEYBINDINGS.md
│   ├── README.event-manager.md
│   ├── README.md
│   ├── README.scripts.md
│   └── config.h
└── examples
    ├── config
    │   ├── README.md
    │   ├── config
    │   └── style.css
    └── data
        ├── bookmarks
        ├── dforms
        │   └── bbs.archlinux.org
        ├── per-site-settings
        ├── scripts
        │   ├── auth.py
        │   ├── download.sh
        │   ├── follow.js
        │   ├── follow.sh
        │   ├── formfiller.js
        │   ├── formfiller.sh
        │   ├── go_input.js
        │   ├── go_input.sh
        │   ├── history.sh
        │   ├── insert_bookmark.sh
        │   ├── insert_temp.sh
        │   ├── instance-select-wmii.sh
        │   ├── load_cookies.sh
        │   ├── load_url_from_bookmarks.sh
        │   ├── load_url_from_history.sh
        │   ├── load_url_from_temps.sh
        │   ├── navigation.js
        │   ├── per-site-settings.py
        │   ├── pipermail.js
        │   ├── scheme.py
        │   ├── session.sh
        │   ├── util
        │   │   ├── dmenu.sh
        │   │   ├── editor.sh
        │   │   ├── uzbl-dir.sh
        │   │   ├── uzbl-util.sh
        │   │   └── uzbl-window.sh
        │   └── uzblcat
        ├── uzbl-logo.svg
        └── uzbl.png

7 directories, 45 files
```

**Comment by mathstuf** [comment]
OK, so it's there…but not being found for some reason. Could you run the following:

```sh
ls -l /usr/local/share/uzbl/examples/config/config
sh -x /usr/local/bin/uzbl-browser
```

**Comment by ghost** [comment]
```
[~]: ls -l /usr/local/share/uzbl/examples/config/config
ls: cannot access '/usr/local/share/uzbl/examples/config/config': Permission denied
[~]: su -
Password: 
# ls -l /usr/local/share/uzbl/examples/config/config
-rw------- 1 root root 23053 Feb 22 01:20 /usr/local/share/uzbl/examples/config/config
# logout
[~]: sh -x /usr/local/bin/uzbl-browser
+ UZBL_PREFIX=/usr/local
+ export UZBL_PREFIX
+ EXAMPLES=/usr/local/share/uzbl/examples
+ XDG_DATA_HOME=/home/myusername/.local/share
+ export XDG_DATA_HOME
+ XDG_DATA_DIRS=/usr/local/share:/usr/share
+ export XDG_DATA_DIRS
+ XDG_CACHE_HOME=/home/myusername/.cache
+ export XDG_CACHE_HOME
+ XDG_CONFIG_HOME=/home/myusername/.config
+ export XDG_CONFIG_HOME
+ mkdir -p /home/myusername/.cache/uzbl /home/myusername/.local/share/uzbl /home/myusername/.config/uzbl
+ '[' -f /home/myusername/.config/uzbl/config ']'
+ '[' -r /usr/local/share/uzbl/examples/config/config ']'
+ die_with_status 3 'Error: Global config not found; please check if your distribution ships them separately'
+ status=3
+ shift
+ echo 'Error: Global config not found; please check if your distribution ships them separately'
Error: Global config not found; please check if your distribution ships them separately
+ exit 3
[~]: sh
[~]: sh -x /usr/local/bin/uzbl-browser
+ UZBL_PREFIX=/usr/local
+ export UZBL_PREFIX
+ EXAMPLES=/usr/local/share/uzbl/examples
+ XDG_DATA_HOME=/home/myusername/.local/share
+ export XDG_DATA_HOME
+ XDG_DATA_DIRS=/usr/local/share:/usr/share
+ export XDG_DATA_DIRS
+ XDG_CACHE_HOME=/home/myusername/.cache
+ export XDG_CACHE_HOME
+ XDG_CONFIG_HOME=/home/myusername/.config                                                                                                                      
+ export XDG_CONFIG_HOME                                                                                                                                    
+ mkdir -p /home/myusername/.cache/uzbl /home/myusername/.local/share/uzbl /home/myusername/.config/uzbl                                                                
+ '[' -f /home/myusername/.config/uzbl/config ']'                                                                                                               
+ '[' -r /usr/local/share/uzbl/examples/config/config ']'                                                                                                   
+ die_with_status 3 'Error: Global config not found; please check if your distribution ships them separately'                                               
+ status=3                                                                                                                                                  
+ shift                                                                                                                                                     
+ echo 'Error: Global config not found; please check if your distribution ships them separately'                                                            
Error: Global config not found; please check if your distribution ships them separately                                                                     
+ exit 3                                                                                                                                                    
[~]: exit
[~]: ls -l /usr/local/bin/uzbl-browser
-rwxr-xr-x 1 root root 2646 Feb 22 01:20 /usr/local/bin/uzbl-browser
```

**Comment by mathstuf** [comment]
OK, so our install rules use `cp -rv` for installing the examples. It should use `$(INSTALL)` with proper permissions instead. Running `chmod -R go+rX /usr/local/share/uzbl/examples` should fix the existing install though.

**Comment by ghost** [comment]
Thanks. Now the program starts with the following console output:
```
[~]: uzbl-browser 

(uzbl-core:30053): GLib-GObject-WARNING **: g_object_set_valist: object class 'GtkLabel' has no property named 'margin'

(uzbl-core:30053): GLib-GObject-WARNING **: g_object_set_valist: object class 'GtkLabel' has no property named 'margin'

(uzbl-core:30053): libsoup-WARNING **: Could not set SSL credentials from '/etc/ssl/certs/ca-bundle.crt': Failed to open file '/etc/ssl/certs/ca-bundle.crt': No such file or directory
awk: cmd. line:4: fatal: cannot open file `/home/myusername/.local/share/uzbl/cookies.txt' for reading (No such file or directory)
awk: cmd. line:4: fatal: cannot open file `/home/myusername/.local/share/uzbl/session-cookies.txt' for reading (No such file or directory)
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-18.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
** Message: PROP_TIMELINE_PROFILING_ENABLED has been deprecated
```
And shows a message:

---
#### Unable to load page

Problem occurred while loading the URL https://uzbl.org/doesitwork/v0.9.1-47-gbdbb81ab

Unacceptable TLS certificate

---

with a "Try again" button.

I obviously have a lot to learn how to use it as the UI is definitely not straightforward :)

**Comment by ghost** [comment]
Also when I quit the program in console it shows:
```
/bin/sh: xclip: command not found
/bin/sh: xclip: command not found

** (uzbl-core:30053): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image
```

**Comment by mathstuf** [comment]
```
awk: cmd. line:4: fatal: cannot open file `/home/myusername/.local/share/uzbl/cookies.txt' for reading (No such file or directory)
```

I thought we were creating these directories before trying to use them, but apparently not.

**Comment by ghost** [comment]
Thanks @mathsuf. I understand this software is still not ready for use so I am going to uninstall it for the moment and check it again at a later time.
